###############

#GPU: [3, 4, 5, 6, 7]
GPU: [0]

VERBOSE: True

MODEL:
  MODE: 'Denoising'
  SESSION: 'MIRNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 8
  NUM_EPOCHS: 10
  LR_INITIAL: 2e-4
  #NEPOCH_DECAY: [40]
  #BETA1: 0.9

TRAINING:
  TRAIN_PS: 128
  VAL_PS: 196
  RESUME: False
  TRAIN_DIR: '../data/gopro_large/train' # path to training data
  VAL_DIR: '../data/gopro_large/test'     # path to validation data
  SAVE_DIR: './checkpoints'          # path to save models and images
  SAVE_IMAGES: True
  VAL_AFTER_EVERY: 1029

